version: '3.4'

services:
  fundadb:
    image: mongo

  topagentsdb:
    image: redis:alpine

  cachingobjectsworkerservice:
    image: ${DOCKER_REGISTRY-}cachingobjectsworkerservice
    build:
      context: .
      dockerfile: src/CachingObjects/CachingObjectsWorkerService/Dockerfile

volumes:
  mongo_data:
