version: '3.4'

services:
  fundadb:
    container_name: fundadb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

   topagentsdb:
    container_name: topagentsdb
    restart: always
    ports:
      - "6379:6379"

  cachingobjectsworkerservice:
    container_name: cachingobjectsworkerservice
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://fundadb:27017/FundaDb"
      - CacheSettings:ConnectionString=basketdb:6379
    depends_on:
      - fundadb
      - topagentsdb